DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (

    ID INT AUTO_INCREMENT  PRIMARY KEY,
    VERSION INT NOT NULL DEFAULT 0,
    CREATED TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP,
    NAME VARCHAR(20) NOT NULL

);